name: Stage & Prod Docker Build, Tag & Push

on:
  push:
    branches: [master]
  release:
    types: [released]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      ENV: ${{ steps.tag.outputs.env }}
      TAG: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Tag & Environment
        id: tag_env
        run: |
          export CI_COMMIT_SHORT_SHA=$(git describe --abbrev=7 --always --tags)
          echo "::set-output name=tag::$CI_COMMIT_SHORT_SHA"
          echo "Commit for this pipeline: ";
          echo $CI_COMMIT_SHORT_SHA;
          if [ ${GITHUB_REF##*/} = "master" ]; then
            export ENV=stage
          else
            export ENV=prod
          fi
          echo "::set-output name=env::$ENV"
          echo "Environment for this pipeline: ";
          echo $ENV

  build-push-image:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: configure-aws-creds
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Pre-build Image
        id: prebuild
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: moderator
          ENV: ${{ needs.prepare.outputs.ENV }}
          TAG: ${{ needs.prepare.outputs.TAG }}
        run: |
          git clone -q https://github.com/discourse/discourse_docker.git
          cd discourse_docker
          git checkout 86b9032bbe75cfd11476c44a5c62f8882dd8ad97
          mkdir -p includes && mkdir -p containers
          cp ../discourse-$ENV.yml containers/app.yml
          cp ../includes/* includes/
          sed -i "s,environment,$ENV," includes/env.yml
          sed -i "s,environment,$ENV," includes/after_build.yml
          sed -i "s,code-revision,$TAG," containers/app.yml
          ./launcher bootstrap app
          docker tag local_discourse/app:latest $ECR_REGISTRY/$ECR_REPOSITORY:$ENV-$TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$ENV-$TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$ENV-$TAG $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
